### ISSUE TITLE
Crash Report with MCPC+

### ISSUE THREAD

**Issue by GenPage** [RS485/NEM-VersionChecker#1]
This is the NEM Community server. I can provide MCPC version if needed. Crashed on loading.

http://pastebin.com/KUnhJMif

**Comment by davboecki** [comment]
This is currently a client Only mod so no server support.

**Comment by GenPage** [comment]
Well im an idiot.

**Comment by bziemons** [comment]
Nope, because that information is not written down anywhere.. yet ;)
